import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdtempSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const base = dirname(fileURLToPath(import.meta.url));
const temp = mkdtempSync(resolve(tmpdir(), 'service-card-guard-'));
mkdirSync(resolve(temp, 'src/core/service-discovery'), { recursive: true });
writeFileSync(resolve(temp, 'card.css'), 'square\r\n');
writeFileSync(resolve(temp, 'src/core/service-discovery/manifest.json'), JSON.stringify({files:{'card.css':createHash('sha256').update('square\n').digest('hex')}}));
execFileSync(process.execPath, [resolve(base, 'verify.mjs')], { cwd: temp });
writeFileSync(resolve(temp, 'card.css'), 'drift');
assert.throws(() => execFileSync(process.execPath, [resolve(base, 'verify.mjs')], { cwd: temp, stdio: 'pipe' }));
const targetArgs = process.argv.slice(2).filter(arg => arg.startsWith('--root=') || arg.startsWith('--target=') || arg === '--existing');
execFileSync(process.execPath, [resolve(base, 'sync.mjs'), '--check', ...targetArgs], { stdio: 'inherit' });
const source = readFileSync(resolve(base, 'src/ServiceDiscoveryDashboard.jsx'), 'utf8');
assert(!source.includes("from '../lib/supabase'"));
assert(source.includes('client.rpc('));
assert(source.includes('onTimer ||'));
assert(source.includes('card.badge && <span className="ls-service-discovery__badge">{card.badge}</span>'));
assert(source.includes("if (a.key === 'english-learning') return -1"));
assert(readFileSync(resolve(base, 'src/ServiceDiscoveryDashboard.css'), 'utf8').includes('aspect-ratio: 1'));
assert(!readFileSync(resolve(base, 'src/ServiceDiscoveryDashboard.css'), 'utf8').includes('grid-template-columns: 1fr;'));
assert(source.includes("'--service-scene-size': 'cover'"));
assert(source.includes("timer: '84% center'"));
assert(source.includes("story: '88% center'"));
assert(source.includes("hpletter: '75% center'"));
assert(source.includes("'--service-scene-position': SCENE_POSITIONS[card.key] || 'center'"));
assert(readFileSync(resolve(base, 'src/ServiceDiscoveryDashboard.css'), 'utf8').includes('background-position: center, var(--service-scene-position, center)'));
console.log('PASS: intact guard, tamper rejected, all consumers identical, injected client/action, square cover and per-card focal points');
